name: Build Unsigned IPA

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-ipa:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.4'
          channel: stable

      - name: Setup iOS Deployment Target
        run: |
          echo "Setting minimum iOS version to 13.0"
          /usr/libexec/PlistBuddy -c "Set MinimumOSVersion 13.0" ios/Runner/Info.plist
          sed -i '' "s/platform :ios, '.*'/platform :ios, '13.0'/" ios/Podfile

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Clean project
        run: |
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock

      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Build iOS (no codesign)
        run: flutter build ios --release --no-codesign --dart-define=CI_BUILD=true

      - name: Create unsigned IPA
        run: |
          mkdir -p build/artifacts/ios
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -R Runner.app Payload/
          zip -r app_unsigned.ipa Payload
          mv app_unsigned.ipa ../../artifacts/ios/
          cd ../../..

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: unsigned-ipa
          path: build/artifacts/ios/app_unsigned.ipa
