workflows:
  ios-unsigned-build:
    name: Build Unsigned IPA
    max_build_duration: 60
    environment:
      flutter: "3.32.4"
      xcode: latest
      cocoapods: default

    scripts:
      - name: Setup iOS Deployment Target
        script: |
          echo "Setting minimum iOS version to 13.0"
          /usr/libexec/PlistBuddy -c "Set MinimumOSVersion 13.0" ios/Runner/Info.plist
          sed -i '' "s/platform :ios, '.*'/platform :ios, '13.0'/" ios/Podfile

      - name: Clean project
        script: |
          flutter clean
          rm -rf ios/Pods ios/Podfile.lock

      - name: Get Flutter dependencies
        script: flutter pub get

      - name: Generate Flutter files
        script: |
          mkdir -p lib/l10n
          touch lib/l10n/app_en.arb || true
          flutter gen-l10n
          if grep -q "build_runner" pubspec.yaml; then
            flutter pub run build_runner build --delete-conflicting-outputs
          fi

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Build iOS (no codesign)
        script: |
          flutter build ios --release --no-codesign --dart-define=CI_BUILD=true

      - name: Create unsigned IPA
        script: |
          mkdir -p build/artifacts/ios
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -R Runner.app Payload/
          zip -r app_unsigned.ipa Payload
          mv app_unsigned.ipa ../../artifacts/ios/
          cd ../../..

      - name: Generate download link
        script: |
          echo "unsigned_ipa_path=artifacts/ios/app_unsigned.ipa" >> $CM_ENV
          echo "IPA_URL=https://$CM_BUILD_ID.codemagic.app/artifacts/ios/app_unsigned.ipa" >> $CM_ENV

    artifacts:
      - build/artifacts/**/*.ipa

    publishing:
      email:
        recipients:
          - mblitmanager@gmail.com
      scripts:
        - name: Notify success
          script: |
            echo "Build successful! Download unsigned IPA:"
            echo $IPA_URL