workflows:
  build-ios-no-sign:
    name: Build iOS without code signing
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get

      - name: Clean Flutter project
        script: flutter clean

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod deintegrate || true
          pod install
          cd ..

      - name: Build iOS release (no code signing)
        script: flutter build ios --release --no-codesign

    - name: Create unsigned IPA
        script: |
          mkdir -p build/artifacts/ios
          cd build/ios/iphoneos
          mkdir -p Payload
          cp -R Runner.app Payload/
          zip -r app_unsigned.ipa Payload
          mv app_unsigned.ipa ../../artifacts/ios/
          cd ../../..

      - name: Generate download link
        script: |
          echo "unsigned_ipa_path=artifacts/ios/app_unsigned.ipa" >> $CM_ENV
          echo "IPA_URL=https://$CM_BUILD_ID.codemagic.app/artifacts/ios/app_unsigned.ipa" >> $CM_ENV

    artifacts:
      - build/artifacts/**/*.ipa

    publishing:
      email:
        recipients:
          - mblitmanager@gmail.com
      scripts:
        - name: Notify success
          script: |
            echo "Build successful! Download unsigned IPA:"
            echo $IPA_URL